name: Build
on:
    - push
jobs:
    run:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        env:
            OS: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@master
            -   name: Install dependencies
                run: npm install
            -   name: Run tests
                run: npm run test
            -   uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
